name: Feature Request
description: Suggest a new feature or improvement for the DLC project
title: "[FEATURE]: "
labels:
  - enhancement
  - triage
assignees:
  - iwannabswiss
body:

  - type: dropdown
    id: application
    attributes:
      label: Application
      description: Which part of the DLC system would this feature affect?
      options:
        - Firmware
        - INDI Driver
        - ASCOM Driver
        - DLC Windows App
        - Other
    validations:
      required: true

  - type: input
    id: feature_title
    attributes:
      label: Feature Title
      description: A short, descriptive title for the feature request
      placeholder: e.g., Add support for XYZ sensor
    validations:
      required: true

  - type: textarea
    id: feature_description
    attributes:
      label: Describe the Feature
      description: Explain the feature or improvement you want and why
      placeholder: Provide details about how this feature should work and its benefits
    validations:
      required: true

  - type: textarea
    id: use_cases
    attributes:
      label: Use Cases
      description: Describe scenarios or problems this feature would solve or improve
      placeholder: e.g., I want to automate XYZ, or it would improve compatibility with ABC
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references
      placeholder: Optional links, screenshots, or info to help understand your request
    validations:
      required: false
